spring:
  datasource:
    url: jdbc:h2:mem:credit_app_request_system_db
    password: 1234
    username: solas
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
